# Generated by Django 4.1.3 on 2022-12-05 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstinmakesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='discription',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='image',
            new_name='img',
        ),
    ]
