# Generated by Django 4.1.3 on 2022-12-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstinmakesapp', '0002_rename_discription_place_desc_rename_image_place_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('pimg', models.ImageField(upload_to='pics')),
                ('pdesc', models.TextField()),
            ],
        ),
    ]
